# Generated by Django 5.0.1 on 2024-01-04 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_demo_app', '0002_alter_todo_created_at_alter_todo_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='uid',
        ),
        migrations.AddField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a541804b-e463-4224-955d-1336de3b5d9a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
